:toc: macro
:node-version: 6
:dev-server-port: 9000

= react-playground

____
Technology showcase of https://facebook.github.io/react/[React] and related tools to build
modern web applications.
____

*WORK IN PROGRESS*

toc::[]

== Common technology stack ==

* https://webpack.js.org/[webpack] with http://babeljs.io/[Babel] using
  https://babeljs.io/docs/plugins/preset-es2015/[ES2015] preset
* http://eslint.org/[ESLint] with https://standardjs.com/[JavaScript Standard Style] rules
* https://stylelint.io/[stylelint] with
  https://github.com/stylelint/stylelint-config-standard[common CSS] rules
* https://github.com/css-modules/css-modules[CSS modules] (_coming soon:_ http://postcss.org/[PostCSS])

As for Internet Explorer(TM), we only care about the officially supported (latest) version for
recent Windows platforms, https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/[and so should you].

== Prototypes ==

* http://localhost:{dev-server-port}/vanilla-react.html[Vanilla React App]
* http://localhost:{dev-server-port}/react-redux.html[React App with Redux] -- Vanilla plus
  http://redux.js.org/[Redux] {amp} https://github.com/reactjs/react-redux[react-redux], featuring
  https://github.com/reactjs/reselect[Reselect] for efficient client state selectors
* http://localhost:{dev-server-port}/react-redux-saga.html[React App with Redux and Saga] -- Redux plus
  https://redux-saga.js.org/[Redux-Saga], featuring https://github.com/gcanti/tcomb[tcomb] for API data
  type validation
* _coming soon:_ https://mobx.js.org/[MobX]

== Development environment ==

. install https://github.com/creationix/nvm[nvm] and run `nvm install v{node-version}.y.z`
  *or* install https://nodejs.org/[Node.js] v{node-version} (LTS) manually on your platform
. install https://yarnpkg.com/[Yarn] (latest stable)
. run `yarn install` to download and link project's dependencies into the local `node_modules`
  directory
. start webpack dev-server via `yarn run start:dev` and JSON API server via `yarn run start:api`
. open the link:#prototypes[prototype page] in your web browser and start hacking!

=== Using webpack dev-server ===

With https://webpack.js.org/configuration/dev-server/[dev-server], all project assets are
processed in-memory (no `dist` directory).

dev-server watches the filesystem and recompiles project assets on change, e.g. JS chunks
whose content is impacted by the source change. Once recompiled, application's HTML page is
automatically reloaded (this is done by injecting a script that opens a WebSocket connection
to the server).

== Basic commands ==

=== `yarn run build` ===

Build project for production. Outputs are placed in `dist` directory. Performs code linting
and runs unit tests before doing the actual build.

=== `yarn run build:dev` ===

Build project for development (without optimizations). Same output location as with `build`
script. No code linting or unit tests, just the build itself.

=== `yarn run start:dev` ===

Starts webpack dev-server, watching the filesystem and recompiling project assets on change.
Serves both project assets and API requests (proxied to JSON API server).

=== `yarn run start:api` ===

Starts JSON API server that imitates a real backend.

=== `yarn run test` ===

TODO implement

=== `yarn run test:watch` ===

TODO implement

== Other commands ==

=== `yarn outdated` ===

Check for outdated dependencies.

=== `yarn check` ===

Validates dependency resolutions in `yarn.lock` based on project's dependencies declared in
`package.json`.

=== `yarn run foo` / `yarn run foo \-- args` ===

Run a locally installed JS module `foo`.

== Good articles ==

* https://github.com/markerikson/react-redux-links[tutorials and resources on React, Redux, ES6 and more]
  (don't get overwhelmed!)
* https://www.robinwieruch.de/redux-mobx-confusion/[dissolving the confusion around Redux and MobX]
* https://goshakkk.name/redux-antipattern-mapstatetoprops/[writing meaningful `mapStateToProps`]
* https://decembersoft.com/posts/a-simple-naming-convention-for-action-creators-in-redux-js/[convention
  to differentiate action creators from action types]

== License ==

https://github.com/vojtechszocs/react-playground/blob/master/LICENSE[MIT]
