:node-version: 6
:dev-server-port: 9000

= react-playground

____
Technology showcase of https://facebook.github.io/react/[React] and related tools to build
modern web applications.
____

*WORK IN PROGRESS*

== Technologies

* https://webpack.js.org/[webpack] with http://babeljs.io/[Babel] using
  https://babeljs.io/docs/plugins/preset-es2015/[ES2015] preset
* http://eslint.org/[ESLint] with https://standardjs.com/[JavaScript Standard Style] rules
* https://stylelint.io/[stylelint] with
  https://github.com/stylelint/stylelint-config-standard[common CSS] rules
* https://github.com/mishoo/UglifyJS2[UglifyJS] and http://cssnano.co/[cssnano] for optimizing
  production builds
* https://facebook.github.io/jest/[Jest] with http://airbnb.io/enzyme/[Enzyme] for testing
  JS code and React components

=== Browser support

The https://github.com/vojtechszocs/react-playground/blob/master/.browserslistrc[Browserslist]
file is used to define supported browsers.

As for Internet Explorer(TM), we only care about the officially supported (latest) version for
recent Windows platforms, https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/[and so should you].

=== Wait, where's the rest of CSS toolchain?

Our webpack CSS loader configuration is minimal on purpose, using the standard `css-loader` with
https://github.com/css-modules/css-modules[CSS Modules] enabled and custom http://cssnano.co/[cssnano]
options for production builds.

For bigger projects, you can use the up-and-coming http://postcss.org/[PostCSS] with its ecosystem
of https://www.postcss.parts/[plugins] or use more traditional tools like http://sass-lang.com/[Sass]
or http://lesscss.org/[Less] that come packed with lots of features out of the box.

== Prototypes

Each prototype is a separate React-based web application built with webpack.

=== http://localhost:{dev-server-port}/vanilla-react.html[Vanilla React App]

* pure React application
* state centralized in top-level `<App>` component

=== http://localhost:{dev-server-port}/react-redux.html[React App with Redux]

_Vanilla React App_ plus:

* http://redux.js.org/[Redux] with https://github.com/reactjs/react-redux[react-redux] bindings
  for predictable state management
* https://github.com/reactjs/reselect[Reselect] for efficient computation of derived data

=== http://localhost:{dev-server-port}/react-redux-saga.html[React App with Redux and Saga]

_React App with Redux_ plus:

* https://redux-saga.js.org/[Redux-Saga] for handling asynchronous operations (like HTTP requests)
  and side effects (like browser `localStorage` access)
* https://github.com/gcanti/tcomb[tcomb] for API data type validation

== Development environment

. install https://github.com/creationix/nvm[nvm] and run `nvm install v{node-version}.y.z`
  *or* install https://nodejs.org/[Node.js] v{node-version} (LTS) manually on your platform
. install https://yarnpkg.com/[Yarn] (latest stable)
. run `yarn install` to download and link project's dependencies into the local `node_modules`
  directory
. start webpack dev-server via `yarn run start:dev` and JSON API server via `yarn run start:api`
. open the link:#prototypes[prototype page] in your web browser and start hacking!

=== webpack dev-server

With https://webpack.js.org/configuration/dev-server/[dev-server], all project assets are
processed in-memory (no `dist` directory).

dev-server watches the filesystem and recompiles project assets on change, regenerating JS
chunks as needed. Once recompiled, application's HTML page is automatically reloaded (this
is done by injecting a script that opens WebSocket connection to dev-server).

=== Testing

There are several types of tests included in this project:

* regular JS unit test:
  https://github.com/vojtechszocs/react-playground/blob/master/src/vanilla/utils.test.js[utils.test.js]

* React component test:
  https://github.com/vojtechszocs/react-playground/blob/master/src/vanilla/NoteFilter.test.js[NoteFilter.test.js]

_Coming up next:_ Redux reducer test, Saga test, async service test (like `remote.js`)

== Basic commands

=== `yarn run build`

Build project for production. Outputs are placed in `dist` directory. Performs code linting
and runs unit tests before doing the actual build.

=== `yarn run build:dev`

Build project for development (without optimizations). Same output location as with `build`
script. No code linting or unit tests, just the build itself.

=== `yarn run start:dev`

Start webpack dev-server, watching the filesystem and recompiling project assets on change.

=== `yarn run start:api`

Start JSON API server that imitates a real backend.

=== `yarn run test`

Run unit tests. Avoids side effects such as automatically creating snapshot files if missing.
Suitable for execution in CI environment.

=== `yarn run test:snap`

Run unit tests and automatically create/update snapshot files if they are missing/conflicting.
Use this *only* when snapshot files need to be created/updated.

=== `yarn run test:watch`

Run unit tests, then watch the filesystem and rerun tests related to changed files.

== Other commands

=== `yarn outdated`

Check for outdated dependencies.

=== `yarn check`

Validate dependency resolutions in `yarn.lock` based on project's dependencies declared in
`package.json`.

=== `yarn run foo` / `yarn run foo \-- args`

Run a locally installed JS module `foo` with optional `args`.

== Good articles

* https://github.com/markerikson/react-redux-links[tutorials and resources on React, Redux, ES6 and more]
  (don't get overwhelmed!)
* https://www.robinwieruch.de/redux-mobx-confusion/[dissolving the confusion around Redux and MobX]
* https://goshakkk.name/redux-antipattern-mapstatetoprops/[writing meaningful `mapStateToProps`]
* https://decembersoft.com/posts/a-simple-naming-convention-for-action-creators-in-redux-js/[convention
  to differentiate action creators from action types]

== License

https://github.com/vojtechszocs/react-playground/blob/master/LICENSE[MIT]
